name: my_weather
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  geolocator: ^13.0.4
  get_it: ^8.0.3
  intl: ^0.20.2
  logger: ^2.5.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
